#!/bin/bash
intern=LVDS-1
extern=HDMI-1

if xrandr --listactivemonitors | grep "$extern"; then
    xrandr --output "$intern" --auto --output "$extern" --off && ~/.fehbg && pkill onboard
	setxkbmap it -option caps:escape
else
	if xrandr | grep "$extern connected"; then
		xrandr --output "$extern" --mode 1600x1200 --output "$intern" --off && ~/.fehbg && setxkbmap us -option
	fi
fi
