#!/bin/sh

site=https://archlinux.beccacervello.it/archlinux/iso/latest
dir=$DOWNLOADS/iso

clear
printf "downloading latest iso\n\n"

wget $site/$(curl -s $site/md5sums.txt 2>&1 | grep "archlinux-[0-9]" | cut -f3 -d " ") -O $dir/archlinux.iso
